In [1]:
import numpy as np

In [2]:
B1 = np.array([[1,0],[0,1]])
B1

array([[1, 0],
       [0, 1]])

In [3]:
B2 = np.array([[2,-2],[1,1]])
B2

array([[ 2, -2],
       [ 1,  1]])

In [5]:
M = np.linalg.inv(B2)
M

array([[ 0.25,  0.5 ],
       [-0.25,  0.5 ]])

In [6]:
v1 = np.array([[8],[6]])
v1

array([[8],
       [6]])

In [8]:
M = np.linalg.inv(np.array([[3],[2]]))
M

LinAlgError: Last 2 dimensions of the array must be square